// Chinese display labels for all BC map components.
// Key = "Type:Style" (matches catalog byStyle keys), Value = Chinese name.
window.MAP_ZH_LABELS = {
  // === 地板 Floor ===
  "Floor:OakWood": "橡木地板",
  "Floor:Stone": "石砖地",
  "Floor:Pavement": "人行道",
  "Floor:Ceramic": "瓷砖",
  "Floor:CeramicDark": "深色瓷砖",
  "Floor:CarpetPink": "粉色地毯",
  "Floor:CarpetBlue": "蓝色地毯",
  "Floor:CarpetRed": "红色地毯",
  "Floor:Padded": "软垫地板",
  "Floor:LatexFloor": "乳胶地板",
  "Floor:Tile": "方格地砖",
  "Floor:HexBlue": "六角蓝砖",
  "Floor:HexPurple": "六角紫砖",
  "Floor:Machine": "机械地板",
  "Floor:HalfWall": "半墙（挡视线）",

  // === 地板·室外 FloorExterior ===
  "FloorExterior:Dirt": "泥土",
  "FloorExterior:Grass": "草地",
  "FloorExterior:LongGrass": "长草",
  "FloorExterior:Sand": "沙地",
  "FloorExterior:Gravel": "碎石",
  "FloorExterior:Asphalt": "沥青路",
  "FloorExterior:Snow": "雪地",
  "FloorExterior:StoneSquareGray": "灰石方砖",
  "FloorExterior:ScatteredLeaves": "落叶",
  "FloorExterior:ScatteredLeavesDirt": "落叶泥地",
  "FloorExterior:ScatteredLeavesThick": "厚落叶",

  // === 墙 Wall ===
  "Wall:MixedWood": "混木板墙",
  "Wall:CedarWood": "雪松墙",
  "Wall:Log": "圆木墙",
  "Wall:Japanese": "日式墙",
  "Wall:Stone": "石墙",
  "Wall:Brick": "砖墙",
  "Wall:Dungeon": "地牢墙",
  "Wall:Square": "方格墙（隔音）",
  "Wall:Steel": "钢墙（隔音）",
  "Wall:Padded": "软垫墙（隔音）",
  "Wall:Tile": "瓷砖墙",
  "Wall:Lattice": "格栅墙",
  "Wall:HexBlue": "六角蓝墙",
  "Wall:HexPurple": "六角紫墙",
  "Wall:PipeBlue": "蓝管墙",
  "Wall:PipePurple": "紫管墙",
  "Wall:SteelBlack": "黑钢墙",
  "Wall:SteelGary": "灰钢墙",

  // === 水域 Water ===
  "Water:Lava": "岩浆",
  "Water:Ocean": "海洋",
  "Water:OceanCalm": "平静海洋",
  "Water:OceanCyan": "青色海",
  "Water:Pool": "泳池",
  "Water:Sea": "浅海",
  "Water:Shallow": "浅水",
  "Water:Swamp": "沼泽",
  "Water:Waves": "波浪",

  // === 门 WallPath ===
  "WallPath:WoodOpen": "木门（开）",
  "WallPath:WoodClosed": "木门（关）",
  "WallPath:WoodLocked": "木门（锁）",
  "WallPath:WoodLockedBronze": "铜锁木门",
  "WallPath:WoodLockedSilver": "银锁木门",
  "WallPath:WoodLockedGold": "金锁木门",
  "WallPath:Metal": "金属门",
  "WallPath:MetalUp": "单向金属门（上）",
  "WallPath:MetalDown": "单向金属门（下）",
  "WallPath:MetalLockedBronze": "铜锁金属门",
  "WallPath:MetalLockedSilver": "银锁金属门",
  "WallPath:MetalLockedGold": "金锁金属门",
  "WallPath:BrownDoor": "棕门",
  "WallPath:BrownDoorOpen": "棕门（开）",
  "WallPath:RoyalDoor": "皇家门",
  "WallPath:RoyalDoorOpen": "皇家门（开）",
  "WallPath:SteelDoor": "钢门",
  "WallPath:SteelDoorOpen": "钢门（开）",
  "WallPath:GrayDoor": "灰门",
  "WallPath:GrayDoorOpen": "灰门（开）",

  // === 钥匙 FloorDecoration ===
  "FloorDecoration:KeyBronze": "铜钥匙",
  "FloorDecoration:KeySilver": "银钥匙",
  "FloorDecoration:KeyGold": "金钥匙",

  // === 标记 FloorDecoration ===
  "FloorDecoration:EntryFlag": "出生点旗帜",
  "FloorDecoration:ExitFlag": "出口旗帜",

  // === 装饰·家具 FloorDecoration ===
  "FloorDecoration:Blank": "空白",
  "FloorDecoration:Bed": "床",
  "FloorDecoration:BedTeal": "青色床",
  "FloorDecoration:ChairWood": "木椅",
  "FloorDecoration:PillowPink": "粉色枕头",
  "FloorDecoration:Stairs": "楼梯",
  "FloorDecoration:TableBrown": "棕色桌子",
  "FloorDecoration:ThroneRed": "红色王座",
  "FloorDecoration:VikingChair": "维京椅",
  "FloorDecoration:AirConditioner": "空调",

  // === 装饰·动物 FloorDecorationAnimal ===
  "FloorDecorationAnimal:Blank": "空白动物位",
  "FloorDecorationAnimal:CatCaramelHappy": "焦糖猫",
  "FloorDecorationAnimal:ChickenBrownIdleLeft": "鸡",
  "FloorDecorationAnimal:DogBrownHappy": "狗",
  "FloorDecorationAnimal:RabbitBrownStand": "兔子",

  // === 装饰·露营 FloorDecorationCamping ===
  "FloorDecorationCamping:Blank": "空白露营位",
  "FloorDecorationCamping:ChairRed": "红椅子",
  "FloorDecorationCamping:Hurdle1": "跨栏1",
  "FloorDecorationCamping:Hurdle2": "跨栏2",
  "FloorDecorationCamping:Hurdle3": "跨栏3",
  "FloorDecorationCamping:LogFire": "篝火",
  "FloorDecorationCamping:LogFireAnim0": "篝火动画",
  "FloorDecorationCamping:LogSingle": "原木",
  "FloorDecorationCamping:SleepingBagBlue": "蓝色睡袋",
  "FloorDecorationCamping:TentBlue": "蓝色帐篷",

  // === 装饰·扩展 FloorDecorationExpanding ===
  "FloorDecorationExpanding:Blank": "空白扩展位",
  "FloorDecorationExpanding:BallPitPreview": "球池预览",
  "FloorDecorationExpanding:BedBluePreview": "蓝床预览",
  "FloorDecorationExpanding:CouchPinkPreview": "粉沙发预览",
  "FloorDecorationExpanding:RailroadPreview": "轨道预览",
  "FloorDecorationExpanding:VikingTablePreview": "维京桌预览",

  // === 装饰·派对 FloorDecorationParty ===
  "FloorDecorationParty:Blank": "空白派对位",
  "FloorDecorationParty:BalloonFiveColor": "五色气球",
  "FloorDecorationParty:BalloonTwoHeart": "爱心气球",
  "FloorDecorationParty:BeachTowelStripe": "条纹沙滩巾",
  "FloorDecorationParty:BeachUmbrellaStripe": "条纹遮阳伞",
  "FloorDecorationParty:FlowerVasePink": "粉色花瓶",
  "FloorDecorationParty:Presents": "礼物盒",
  "FloorDecorationParty:Speaker": "音箱",
  "FloorDecorationParty:WeddingArch": "婚礼拱门",
  "FloorDecorationParty:WeddingCake": "婚礼蛋糕",

  // === 装饰·主题 FloorDecorationThemed ===
  "FloorDecorationThemed:Blank": "空白主题位",
  "FloorDecorationThemed:BanzaiTree": "万岁树",
  "FloorDecorationThemed:BondageClubBanner": "BC横幅",
  "FloorDecorationThemed:Cabinet": "柜子",
  "FloorDecorationThemed:ConsoleLeft": "左控制台",
  "FloorDecorationThemed:ConsoleRight": "右控制台",
  "FloorDecorationThemed:DeskBlue": "蓝色书桌",
  "FloorDecorationThemed:DeskPurple": "紫色书桌",
  "FloorDecorationThemed:IroningBoard": "熨衣板",
  "FloorDecorationThemed:JapaneseTable": "日式矮桌",
  "FloorDecorationThemed:KatanaOnStand": "武士刀架",
  "FloorDecorationThemed:LaundryMachine": "洗衣机",
  "FloorDecorationThemed:LongDeskLeft": "长桌左",
  "FloorDecorationThemed:LongDeskRight": "长桌右",
  "FloorDecorationThemed:MagicMark": "魔法印记",
  "FloorDecorationThemed:MedicalDesk": "医疗桌",
  "FloorDecorationThemed:ShibariFrame": "缚绳架",
  "FloorDecorationThemed:SinkDishes": "水槽",
  "FloorDecorationThemed:StandingBellflowerBanner": "风铃草旗",
  "FloorDecorationThemed:StudentDesk": "学生课桌",
  "FloorDecorationThemed:TeacherDesk": "教师讲台",
  "FloorDecorationThemed:Television": "电视",
  "FloorDecorationThemed:TelevisionBack": "电视背面",
  "FloorDecorationThemed:Toilet": "马桶",
  "FloorDecorationThemed:VoidOrderBanner": "虚空教团旗",
  "FloorDecorationThemed:Wardrobe": "衣柜",

  // === 障碍物 FloorObstacle ===
  "FloorObstacle:Blank": "空白障碍位",
  "FloorObstacle:Stalagmite": "石笋",
  "FloorObstacle:Rocks": "岩石堆",
  "FloorObstacle:GoldStones": "金石堆",
  "FloorObstacle:StonePile": "石堆",
  "FloorObstacle:Statue": "雕像",
  "FloorObstacle:Knight": "骑士像",
  "FloorObstacle:Samurai": "武士像",
  "FloorObstacle:Totem": "图腾柱",
  "FloorObstacle:EasterIsland": "复活节岛石像",
  "FloorObstacle:OrderOfTheVoidTotem": "虚空教团图腾",
  "FloorObstacle:Barrel": "木桶",
  "FloorObstacle:Chest": "宝箱",
  "FloorObstacle:IronBars": "铁栏杆",
  "FloorObstacle:BarbFence": "刺网围栏",
  "FloorObstacle:PicketFence": "尖桩篱笆",
  "FloorObstacle:VelourRopeBarrier": "天鹅绒绳栏",
  "FloorObstacle:Bush": "灌木丛",
  "FloorObstacle:OakTree": "橡树",
  "FloorObstacle:OakTree_Fall": "倒下的橡树",
  "FloorObstacle:LeaflessTree": "枯树",
  "FloorObstacle:PineTree": "松树",
  "FloorObstacle:PalmTree": "棕榈树",
  "FloorObstacle:Sakura": "樱花树",
  "FloorObstacle:Cactus": "仙人掌",
  "FloorObstacle:ChristmasTree": "圣诞树",
  "FloorObstacle:Window": "窗户",
  "FloorObstacle:TrashCan": "垃圾桶",
  "FloorObstacle:RoadCone": "路锥",
  "FloorObstacle:LampPost": "路灯",
  "FloorObstacle:Pillar": "石柱",

  // === 道具 FloorItem ===
  "FloorItem:Blank": "空白道具位",
  "FloorItem:BondageBench": "束缚长凳",
  "FloorItem:Coffin": "棺材",
  "FloorItem:FuturisticCrate": "未来箱",
  "FloorItem:Kennel": "犬笼",
  "FloorItem:Locker": "储物柜",
  "FloorItem:MedicalBed": "医疗床",
  "FloorItem:Pole": "立柱",
  "FloorItem:TheDisplayFrame": "展示框",
  "FloorItem:Trolley": "手推车",
  "FloorItem:WoodenBox": "木箱",
  "FloorItem:X-Cross": "十字架",

  // === 字母/数字/图标 ===
  "FloorLetter:Blank": "空白字母",
  "FloorNumber:Blank": "空白数字",
  "FloorIcon:Blank": "空白图标",
  "FloorIcon:IconArrowDown": "↓箭头",
  "FloorIcon:IconArrowLeft": "←箭头",
  "FloorIcon:IconArrowRight": "→箭头",
  "FloorIcon:IconArrowUp": "↑箭头",
  "FloorIcon:IconCircle": "圆形",
  "FloorIcon:IconCross": "叉号",
  "FloorIcon:IconDiamond": "菱形",
  "FloorIcon:IconSquare": "方形",
  "FloorIcon:IconTriangle": "三角形",

  // === 旗 Banners ===
  "Banners:BellflowerBanner": "风铃草旗",
  "Banners:Black": "黑色旗",
  "Banners:Blue": "蓝色旗",
  "Banners:BondageClub": "BC旗",
  "Banners:Green": "绿色旗",
  "Banners:Inquisition": "宗教裁判所旗",
  "Banners:MagesSacrosanctorum": "圣法师旗",
  "Banners:MaidSorority": "女仆会旗",
  "Banners:PaladinBanner": "圣骑士旗",
  "Banners:Priesthood": "祭司旗",
  "Banners:Red": "红色旗",
  "Banners:ServiOrdinisBanner": "秩序之仆旗",
  "Banners:VoidOrder": "虚空教团旗",
  "Banners:Yellow": "黄色旗",

  // === 墙面装饰 WallDecoration ===
  "WallDecoration:Blank": "空白墙面装饰",
  "WallDecoration:AirConditioner": "墙面空调",
  "WallDecoration:Bookshelf": "书架",
  "WallDecoration:Candelabra0": "烛台",
  "WallDecoration:CrossedSabers": "交叉佩刀",
  "WallDecoration:EnemaHead": "灌肠器",
  "WallDecoration:EyeTest": "视力表",
  "WallDecoration:Fireplace": "壁炉",
  "WallDecoration:FirstAidKit": "急救箱",
  "WallDecoration:Mirror": "镜子",
  "WallDecoration:MonitorBigLeft": "大屏左",
  "WallDecoration:MonitorBigRight": "大屏右",
  "WallDecoration:MonitorSmall": "小屏幕",
  "WallDecoration:Moss": "苔藓",
  "WallDecoration:Painting": "画作",
  "WallDecoration:SchoolBoard": "学校公告板",
  "WallDecoration:Scroll": "卷轴",
  "WallDecoration:ShowerHead": "淋浴喷头",
  "WallDecoration:SilverShield": "银盾牌",
  "WallDecoration:StainedGlass": "彩色玻璃窗",
  "WallDecoration:Stocking": "圣诞袜",
  "WallDecoration:Vines": "藤蔓",
  "WallDecoration:Vines2": "藤蔓2",
  "WallDecoration:Wanted": "通缉令",
  "WallDecoration:Whip": "鞭子",
  "WallDecoration:Window": "窗户",
  "WallDecoration:WindowNight": "夜间窗户",
};
